name: CI — tests and deploy

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (optional)
        run: |
          npm ci || true

      - name: Install Puppeteer
        run: |
          npm install --no-save puppeteer

      - name: Run VM runtime test
        run: |
          node tests/check_runtime.js

      - name: Run headless browser test (Puppeteer)
        run: |
          node tests/browser_check.js

      - name: Deploy to Vercel
        if: ${{ secrets.VERCEL_TOKEN != '' }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "VERCEL_TOKEN found — deploying to Vercel"
          npx vercel --prod --yes --token "$VERCEL_TOKEN"
      - name: Skip deploy notice
        if: ${{ secrets.VERCEL_TOKEN == '' }}
        run: |
          echo "VERCEL_TOKEN is not set in repository secrets — skipping deploy step. To enable deploy, add VERCEL_TOKEN to Secrets." 
